### ISSUE TITLE
李老师您好，数据集文件无法下载，请恢复一下

### ISSUE THREAD

**Issue by LZhongYue** [li-yapeng/DSECN#1]
数据集文件被删除，请求恢复

**Comment by LZhongYue** [comment]
![image](https://github.com/li-yapeng/DSECN/assets/66252224/8a05762d-6683-4e97-a8de-4f0bc0e927dc)
![屏幕截图 2024-07-02 184428](https://github.com/li-yapeng/DSECN/assets/66252224/fff7d828-71e9-4cea-bced-cae76e450d27)

**Comment by li-yapeng** [comment]
已在README中更新了Google Drive和百度网盘链接。

Google Drive: 
         https://drive.google.com/uc?id=1Gy3dvusCumvTcQ4uUg9W1EkWrkNca6Ak
百度网盘：
         https://pan.baidu.com/s/1fyKRMxUqCW8UKhxGyCxzjw?pwd=zjoo

**Comment by rongtongxueya** [comment]
hello，非常非常好的工作，我最近在研究零样本分类，我遇到了一个问题比较困惑，请问您可以公开数据制作的代码吗，这个mat文件属性信息的向量化以及用restent提取图像特征的代码吗，我想从数据的制作全面的了解一下零样本分类。我自己用同一个模型bert提取的属性向量，两次提取的不一样，我有点困惑自己哪里做错了

**Comment by li-yapeng** [comment]
已上传构建数据集代码，包含 ResNet图像特征和CLIP语义表示提取代码示例，至[(generate_data_utils)](https://github.com/li-yapeng/DSECN/tree/main/generate_data_utils).

就两次特征提取不同的问题，可能的情况有点多，比如：prompt设置、运行环境、运行参数、model.eval()是否打开等等。也可以分析下两次生成的特征差异有多大。采用相同数据集划分时，两次生成特征对分类结果的影响有多大。
